# Generated by Django 3.2.12 on 2022-02-08 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='viewcount',
        ),
    ]
