# Generated by Django 3.2.12 on 2022-02-08 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_post_viewcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='nextpost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_post', to='blog.post'),
        ),
        migrations.AddField(
            model_name='post',
            name='prevpost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_post', to='blog.post'),
        ),
    ]
